### ISSUE TITLE
failed to read delta table which was converted from parquet to delta using delta-spark  (Schema error: No such field: deletionVector)

### ISSUE THREAD

**Issue by neom-hpunetha** [duckdb/duckdb_delta#55]
I have a delta table which was created from parquet using DeltaTable.convertToDelta function (reference - https://delta.io/blog/2022-09-23-convert-parquet-to-delta/).
I am able to read it within pyspark using delta spark, however it gives error on opening via duckdb.
Also, I am using delta-spark version 2.0.0 and for my use-case

I get below error -
SQL Error: java.sql.SQLException: IO Error: Hit DeltaKernel FFI error (from: While trying to read from delta table: 'D:\duckdb_cli\deltatables\devices/'): Hit error: 2 (ArrowError) with message (Schema error: No such field: deletionVector)

Am I doing something wrong? , is there a fix for this?

**Comment by SEEK-AzwanZuharimi** [comment]
Having the same error

**Comment by aeaston1** [comment]
I had the same error on duckdb v1.0.0, upgraded to latest (v1.1.3) and this problem went away - double check you know exactly which version you are using! That was my issue at least...

**Comment by neom-hpunetha** [comment]
@aeaston1 
Thanks, yes, I forgot to update the comment here but in my case, after updating to v1.1.0, it was fixed for me.
This could be closed.
